project:
  type: website
  output-dir: docs

website:
  title: "Steffen Aasen"
  navbar:
    left:
      # - href: index.qmd
        # text: void
      - about.qmd
      - href: another.qmd
  page-footer:
    background: "#4e2b86"
    left:
      - "Testing"
    right:
      - "Text"
      - icon: github
        href: https://github.com/a-asen

format:
  html:
    theme:
      dark: [darkly, theme-add.scss]
    css: styles.css
    toc: true



