project:
  type: website
  output-dir: docs

website:
  title: "Steffen Rygg Aasen"
  navbar:
    left:
      - publications/index.qmd
      - other-work/index.qmd
    right:
      - icon: github
        href: https://github.com/a-asen
  page-footer:
    background: "#4e2b86"
    left:
      - "Copyright 2024, Steffen Rygg Aasen"
    right:
      - "Text"
      - icon: github
        href: https://github.com/a-asen

format:
  html:
    theme:
      dark: [darkly, themes/theme-dark-add.scss]
      light: [flatly, themes/theme-light-add.scss]
    toc: true



